### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by milesgranger** [jackoalan/lzokay#4]
Hi,

I'm interested in porting LZO to another language as well, but see it's GPLv2. My understanding was that this was quite pervasive, covering even "work derived". However, I see you have this under MIT; which is what I'm after as well. I am a license novice, so just wanted to understand better if relicensing from implementation is acceptable or if you maybe contacted the author directly?

Thanks for the help!

**Comment by Antidote** [comment]
You can't relicense, but MIT is permissive enough that you can use it as long as you credit Jack and include the original license.

**Comment by milesgranger** [comment]
I don't know how accurate that is, GPL basically says it can't be used in proprietary software, and this spans to include derived work from the original source. MIT allows, of course, use in proprietary software. What you're describing is BSD genre of licensing.

**Comment by milesgranger** [comment]
Maybe you're thinking I want to re-implement LZO again from this C++ implementation; which is under MIT. My question was how did this project manage to get it MIT licensed when the _original_ C implementation was GPLv2 licensed. ref: http://www.oberhumer.com/opensource/lzo/

**Comment by milesgranger** [comment]
From the source code, it seems like the original implementation wasn't used, but docs from some broken URL: https://github.com/jackoalan/lzokay/blob/546a9695271e8a8b4711383f828172754fd825f2/lzokay.cpp#L6 I _think_ maybe this is how it was done, as I'm pretty sure implementing something with a restrictive license is okay if it's instead implemented from papers/something else other than project itself which implements it with the restrictive license. 

Will assume this is how it was done then, and close this issue. Thanks! Please feel free to clarify if I have it wrong.
